name: Dev/Staging BCentral Release

on:
  workflow_dispatch:
    inputs:
      bal_central_environment:
        description: Ballerina Central Environment
        type: choice
        options:
        - STAGE
        - DEV
        required: true

jobs:
    release:
        runs-on: ubuntu-latest
        env: 
          BALLERINA_${{ github.event.inputs.bal_central_environment }}_CENTRAL: true
        steps:
            - uses: actions/checkout@v2
                
            # Build the ballerina project
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.4.1
              with:
                  args:
                      pack ./gsheet

            # Push the package to Ballerina central - Staging
            - name: Push to Staging
              if: github.event.inputs.bal_central_environment == 'STAGE'
              uses: ballerina-platform/ballerina-action/@2201.4.1
              with:
                  args:
                      push
              env:
                  WORKING_DIR: ./gsheet
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
            
            # Push the package to Ballerina central - Dev
            - name: Push to Dev
              if: github.event.inputs.bal_central_environment == 'DEV'
              uses: ballerina-platform/ballerina-action/@2201.2.1
              with:
                  args:
                      push
              env:
                  WORKING_DIR: ./gsheet
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
