name: Deployment

# Controls when the action will run.
# Triggers the workflow on release.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Build the ballerina project
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@2201.4.1
              with:
                  args:
                      pack ./gsheet
              env:
                CLIENT_ID: ${{ secrets.CLIENT_ID }}
                CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
                REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

            # Push the module to the Ballerina central
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@2201.4.1
              with:
                  args:
                      push
              env:
                  WORKING_DIR: ./gsheet
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
